"""remove_global_roles_add_circle_role

Revision ID: cbd5972b0e0e
Revises: 70f30a12c96c
Create Date: 2026-02-25 11:16:37.279222

"""
from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'cbd5972b0e0e'
down_revision: str | Sequence[str] | None = '70f30a12c96c'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('circle_members', sa.Column('role', sa.String(length=20), nullable=False))
    op.create_foreign_key(None, 'circle_members', 'users', ['user_id'], ['id'])
    op.create_foreign_key(None, 'circle_members', 'circles', ['circle_id'], ['id'])
    op.drop_column('circle_members', 'is_moderator')
    op.drop_column('circle_members', 'is_admin')
    op.drop_index(op.f('ix_circles_name'), table_name='circles')
    op.create_foreign_key(None, 'circles', 'users', ['owner_id'], ['id'])
    op.drop_index(op.f('ix_posts_author_id'), table_name='posts')
    op.drop_index(op.f('ix_posts_circle_id'), table_name='posts')
    op.create_foreign_key(None, 'posts', 'circles', ['circle_id'], ['id'])
    op.create_foreign_key(None, 'posts', 'users', ['author_id'], ['id'])
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.create_unique_constraint(None, 'users', ['username'])
    op.create_unique_constraint(None, 'users', ['email'])
    op.drop_column('users', 'role_id')
    op.drop_column('users', 'updated_at')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('role_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_constraint(None, 'users', type_='unique')
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.drop_constraint(None, 'posts', type_='foreignkey')
    op.drop_constraint(None, 'posts', type_='foreignkey')
    op.create_index(op.f('ix_posts_circle_id'), 'posts', ['circle_id'], unique=False)
    op.create_index(op.f('ix_posts_author_id'), 'posts', ['author_id'], unique=False)
    op.drop_constraint(None, 'circles', type_='foreignkey')
    op.create_index(op.f('ix_circles_name'), 'circles', ['name'], unique=True)
    op.add_column('circle_members', sa.Column('is_admin', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.add_column('circle_members', sa.Column('is_moderator', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'circle_members', type_='foreignkey')
    op.drop_constraint(None, 'circle_members', type_='foreignkey')
    op.drop_column('circle_members', 'role')
    # ### end Alembic commands ###
