"""Refactor CircleMember to use booleans

Revision ID: e2f23dba411a
Revises: 0afb44b7983e
Create Date: 2026-02-12 12:07:37.240181

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e2f23dba411a'
down_revision: Union[str, Sequence[str], None] = '0afb44b7983e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('circle_members', sa.Column('is_admin', sa.Boolean(), nullable=False))
    op.add_column('circle_members', sa.Column('is_moderator', sa.Boolean(), nullable=False))
    op.drop_column('circle_members', 'role_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('circle_members', sa.Column('role_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_column('circle_members', 'is_moderator')
    op.drop_column('circle_members', 'is_admin')
    # ### end Alembic commands ###
